// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrEdF4iwjIFoVv3ufSwQze_zbZEpi8lLY',
    appId: '1:880531573834:web:7cbfd29d8c9b6425156ab3',
    messagingSenderId: '880531573834',
    projectId: 'carwash-5e1a5',
    authDomain: 'carwash-5e1a5.firebaseapp.com',
    storageBucket: 'carwash-5e1a5.firebasestorage.app',
    measurementId: 'G-95JS96DLTY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5KuHd69Tff7LIWxz1h10rGatCgXDk31M',
    appId: '1:880531573834:ios:82ac10a2ad85d375156ab3',
    messagingSenderId: '880531573834',
    projectId: 'carwash-5e1a5',
    storageBucket: 'carwash-5e1a5.firebasestorage.app',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5KuHd69Tff7LIWxz1h10rGatCgXDk31M',
    appId: '1:880531573834:ios:82ac10a2ad85d375156ab3',
    messagingSenderId: '880531573834',
    projectId: 'carwash-5e1a5',
    storageBucket: 'carwash-5e1a5.firebasestorage.app',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrEdF4iwjIFoVv3ufSwQze_zbZEpi8lLY',
    appId: '1:880531573834:web:cdc1499d74988175156ab3',
    messagingSenderId: '880531573834',
    projectId: 'carwash-5e1a5',
    authDomain: 'carwash-5e1a5.firebaseapp.com',
    storageBucket: 'carwash-5e1a5.firebasestorage.app',
    measurementId: 'G-C4XYWL76BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRFSMnl8V_7_Y4Lpp_SGGmuslUpfjPhlQ',
    appId: '1:880531573834:android:e497cb65effa4a88156ab3',
    messagingSenderId: '880531573834',
    projectId: 'carwash-5e1a5',
    storageBucket: 'carwash-5e1a5.firebasestorage.app',
  );

}